//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace System.Device
{
    public partial record ComponentInformation
    {
        public ComponentInformation(object instance, string description) { }

        public string Description { get { throw null; } init { } }

        protected object Instance { get { throw null; } }

        public string Name { get { throw null; } }

        public Collections.Generic.IDictionary<string, string> Properties { get { throw null; } init { } }

        public Collections.Generic.IReadOnlyList<ComponentInformation> SubComponents { get { throw null; } }

        public virtual void AddSubComponent(ComponentInformation subComponent) { }

        protected virtual void SubComponentsToString(Text.StringBuilder output, int ident) { }

        public override string ToString() { throw null; }
    }
}

namespace System.Device.Gpio
{
    public partial class GpioController : IDisposable
    {
        public GpioController() { }

        public GpioController(GpioDriver driver) { }

        [Obsolete]
        public GpioController(PinNumberingScheme numberingScheme, GpioDriver driver) { }

        [Obsolete]
        public GpioController(PinNumberingScheme numberingScheme) { }

        [Obsolete]
        public PinNumberingScheme NumberingScheme { get { throw null; } }

        public virtual int PinCount { get { throw null; } }

        public void ClosePin(int pinNumber) { }

        protected virtual void ClosePinCore(int pinNumber) { }

        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        protected virtual int GetLogicalPinNumber(int pinNumber) { throw null; }

        public virtual PinMode GetPinMode(int pinNumber) { throw null; }

        public virtual bool IsPinModeSupported(int pinNumber, PinMode mode) { throw null; }

        public virtual bool IsPinOpen(int pinNumber) { throw null; }

        public GpioPin OpenPin(int pinNumber, PinMode mode, PinValue initialValue) { throw null; }

        public GpioPin OpenPin(int pinNumber, PinMode mode) { throw null; }

        public GpioPin OpenPin(int pinNumber) { throw null; }

        protected virtual void OpenPinCore(int pinNumber) { }

        public virtual ComponentInformation QueryComponentInformation() { throw null; }

        public virtual PinValue Read(int pinNumber) { throw null; }

        public void Read(Span<PinValuePair> pinValuePairs) { }

        public virtual void RegisterCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback) { }

        public virtual void SetPinMode(int pinNumber, PinMode mode) { }

        public virtual void Toggle(int pinNumber) { }

        public virtual void UnregisterCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback) { }

        public virtual WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        public WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, TimeSpan timeout) { throw null; }

        public virtual Threading.Tasks.ValueTask<WaitForEventResult> WaitForEventAsync(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken token) { throw null; }

        [Diagnostics.DebuggerStepThrough]
        public Threading.Tasks.ValueTask<WaitForEventResult> WaitForEventAsync(int pinNumber, PinEventTypes eventTypes, TimeSpan timeout) { throw null; }

        public virtual void Write(int pinNumber, PinValue value) { }

        public void Write(ReadOnlySpan<PinValuePair> pinValuePairs) { }
    }

    public abstract partial class GpioDriver : IDisposable
    {
        protected internal abstract int PinCount { get; }

        protected internal abstract void AddCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback);
        protected internal abstract void ClosePin(int pinNumber);
        protected internal abstract int ConvertPinNumberToLogicalNumberingScheme(int pinNumber);
        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        ~GpioDriver() {
        }

        protected internal abstract PinMode GetPinMode(int pinNumber);
        protected internal abstract bool IsPinModeSupported(int pinNumber, PinMode mode);
        protected internal abstract void OpenPin(int pinNumber);
        public virtual ComponentInformation QueryComponentInformation() { throw null; }

        protected internal abstract PinValue Read(int pinNumber);
        protected internal abstract void RemoveCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback);
        protected internal virtual void SetPinMode(int pinNumber, PinMode mode, PinValue initialValue) { }

        protected internal abstract void SetPinMode(int pinNumber, PinMode mode);
        protected internal virtual void Toggle(int pinNumber) { }

        protected internal abstract WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken);
        protected internal virtual Threading.Tasks.ValueTask<WaitForEventResult> WaitForEventAsync(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        protected internal abstract void Write(int pinNumber, PinValue value);
    }

    public partial class GpioPin : MarshalByRefObject, IEquatable<GpioPin>, IDisposable
    {
        protected internal GpioPin(int pinNumber, GpioController controller) { }

        public GpioController Controller { get { throw null; } }

        public virtual int PinNumber { get { throw null; } }

        public virtual event PinChangeEventHandler ValueChanged { add { } remove { } }

        public virtual void Close() { }

        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        public virtual bool Equals(GpioPin? other) { throw null; }

        public override bool Equals(object? obj) { throw null; }

        public override int GetHashCode() { throw null; }

        public virtual PinMode GetPinMode() { throw null; }

        public virtual bool IsPinModeSupported(PinMode pinMode) { throw null; }

        public virtual PinValue Read() { throw null; }

        public virtual void SetPinMode(PinMode value) { }

        public virtual void Toggle() { }

        public virtual void Write(PinValue value) { }
    }

    public delegate void PinChangeEventHandler(object sender, PinValueChangedEventArgs pinValueChangedEventArgs);
    [Flags]
    public enum PinEventTypes
    {
        None = 0,
        Rising = 1,
        Falling = 2
    }

    public enum PinMode
    {
        Input = 0,
        Output = 1,
        InputPullDown = 2,
        InputPullUp = 3
    }

    [Obsolete]
    public enum PinNumberingScheme
    {
        Logical = 0,
        Board = 1
    }

    public readonly partial struct PinValue : IEquatable<PinValue>
    {
        private readonly int _dummyPrimitive;
        public static PinValue High { get { throw null; } }

        public static PinValue Low { get { throw null; } }

        public readonly bool Equals(PinValue other) { throw null; }

        public override readonly bool Equals(object? obj) { throw null; }

        public override readonly int GetHashCode() { throw null; }

        public static bool operator ==(PinValue a, PinValue b) { throw null; }

        public static explicit operator bool(PinValue value) { throw null; }

        public static explicit operator byte(PinValue value) { throw null; }

        public static explicit operator int(PinValue value) { throw null; }

        public static implicit operator PinValue(bool value) { throw null; }

        public static implicit operator PinValue(int value) { throw null; }

        public static bool operator !=(PinValue a, PinValue b) { throw null; }

        public static PinValue operator !(PinValue v) { throw null; }

        public override readonly string ToString() { throw null; }
    }

    public partial class PinValueChangedEventArgs : EventArgs
    {
        public PinValueChangedEventArgs(PinEventTypes changeType, int pinNumber) { }

        public PinEventTypes ChangeType { get { throw null; } }

        public int PinNumber { get { throw null; } }
    }

    public readonly partial struct PinValuePair
    {
        private readonly int _dummyPrimitive;
        public PinValuePair(int pinNumber, PinValue pinValue) { }

        public int PinNumber { get { throw null; } }

        public PinValue PinValue { get { throw null; } }

        public readonly void Deconstruct(out int pinNumber, out PinValue pinValue) { throw null; }
    }

    public partial struct WaitForEventResult
    {
        public PinEventTypes EventTypes;
        public bool TimedOut;
    }
}

namespace System.Device.Gpio.Drivers
{
    [Diagnostics.CodeAnalysis.Experimental("SDGPIO0001", UrlFormat = "https://aka.ms/dotnet-iot-warnings/{0}")]
    public partial class GpiodException : IO.IOException
    {
        public GpiodException() { }

        public GpiodException(string message, Exception inner) { }

        public GpiodException(string message) { }
    }

    public partial class LibGpiodDriver : UnixDriver
    {
        [Diagnostics.CodeAnalysis.Experimental("SDGPIO0001", UrlFormat = "https://aka.ms/dotnet-iot-warnings/{0}")]
        public LibGpiodDriver(int gpioChip, LibGpiodDriverVersion driverVersion) { }

        public LibGpiodDriver(int gpioChip = 0) { }

        protected internal override int PinCount { get { throw null; } }

        [Diagnostics.CodeAnalysis.Experimental("SDGPIO0001", UrlFormat = "https://aka.ms/dotnet-iot-warnings/{0}")]
        public LibGpiodDriverVersion Version { get { throw null; } protected set { } }

        protected internal override void AddCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback) { }

        protected internal override void ClosePin(int pinNumber) { }

        protected internal override int ConvertPinNumberToLogicalNumberingScheme(int pinNumber) { throw null; }

        protected override void Dispose(bool disposing) { }

        [Diagnostics.CodeAnalysis.Experimental("SDGPIO0001", UrlFormat = "https://aka.ms/dotnet-iot-warnings/{0}")]
        public static LibGpiodDriverVersion[] GetAvailableVersions() { throw null; }

        protected internal override PinMode GetPinMode(int pinNumber) { throw null; }

        protected internal override bool IsPinModeSupported(int pinNumber, PinMode mode) { throw null; }

        protected internal override void OpenPin(int pinNumber) { }

        public override ComponentInformation QueryComponentInformation() { throw null; }

        protected internal override PinValue Read(int pinNumber) { throw null; }

        protected internal override void RemoveCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback) { }

        protected internal override void SetPinMode(int pinNumber, PinMode mode, PinValue initialValue) { }

        protected internal override void SetPinMode(int pinNumber, PinMode mode) { }

        protected internal override void Toggle(int pinNumber) { }

        protected internal override WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        protected internal override void Write(int pinNumber, PinValue value) { }
    }

    [Diagnostics.CodeAnalysis.Experimental("SDGPIO0001", UrlFormat = "https://aka.ms/dotnet-iot-warnings/{0}")]
    public enum LibGpiodDriverVersion
    {
        V1 = 0,
        V2 = 1
    }

    public partial class RaspberryPi3Driver : GpioDriver
    {
        public bool AlternatePinModeSettingSupported { get { throw null; } }

        protected ulong ClearRegister { get { throw null; } set { } }

        protected internal override int PinCount { get { throw null; } }

        protected ulong SetRegister { get { throw null; } set { } }

        protected internal override void AddCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback) { }

        protected internal override void ClosePin(int pinNumber) { }

        protected internal override int ConvertPinNumberToLogicalNumberingScheme(int pinNumber) { throw null; }

        protected override void Dispose(bool disposing) { }

        public AltMode GetAlternatePinMode(int pinNumber) { throw null; }

        protected internal override PinMode GetPinMode(int pinNumber) { throw null; }

        protected internal override bool IsPinModeSupported(int pinNumber, PinMode mode) { throw null; }

        protected internal override void OpenPin(int pinNumber) { }

        public override ComponentInformation QueryComponentInformation() { throw null; }

        protected internal override PinValue Read(int pinNumber) { throw null; }

        protected internal override void RemoveCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback) { }

        public void SetAlternatePinMode(int pinNumber, AltMode altPinMode) { }

        protected internal override void SetPinMode(int pinNumber, PinMode mode, PinValue initialValue) { }

        protected internal override void SetPinMode(int pinNumber, PinMode mode) { }

        protected internal override void Toggle(int pinNumber) { }

        protected internal override WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        protected internal override Threading.Tasks.ValueTask<WaitForEventResult> WaitForEventAsync(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        protected internal override void Write(int pinNumber, PinValue value) { }

        public enum AltMode
        {
            Unknown = 0,
            Input = 1,
            Output = 2,
            Alt0 = 3,
            Alt1 = 4,
            Alt2 = 5,
            Alt3 = 6,
            Alt4 = 7,
            Alt5 = 8
        }
    }

    public partial class SysFsDriver : UnixDriver
    {
        protected internal override int PinCount { get { throw null; } }

        protected internal override void AddCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback) { }

        protected internal override void ClosePin(int pinNumber) { }

        protected internal override int ConvertPinNumberToLogicalNumberingScheme(int pinNumber) { throw null; }

        protected override void Dispose(bool disposing) { }

        protected internal override PinMode GetPinMode(int pinNumber) { throw null; }

        protected internal override bool IsPinModeSupported(int pinNumber, PinMode mode) { throw null; }

        protected internal override void OpenPin(int pinNumber) { }

        protected internal override PinValue Read(int pinNumber) { throw null; }

        protected internal override void RemoveCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback) { }

        protected internal override void SetPinMode(int pinNumber, PinMode mode) { }

        protected internal override void Toggle(int pinNumber) { }

        protected internal override WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, Threading.CancellationToken cancellationToken) { throw null; }

        protected internal override void Write(int pinNumber, PinValue value) { }
    }

    public abstract partial class UnixDriver : GpioDriver
    {
        public static UnixDriver Create() { throw null; }
    }
}

namespace System.Device.I2c
{
    public abstract partial class I2cBus : IDisposable
    {
        public static I2cBus Create(int busId) { throw null; }

        public abstract I2cDevice CreateDevice(int deviceAddress);
        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        public virtual ComponentInformation QueryComponentInformation() { throw null; }

        public abstract void RemoveDevice(int deviceAddress);
    }

    public sealed partial class I2cConnectionSettings : IEquatable<I2cConnectionSettings>
    {
        public I2cConnectionSettings(int busId, int deviceAddress) { }

        public int BusId { get { throw null; } }

        public int DeviceAddress { get { throw null; } }

        public bool Equals(I2cConnectionSettings? other) { throw null; }

        public override bool Equals(object? obj) { throw null; }

        public override int GetHashCode() { throw null; }
    }

    public abstract partial class I2cDevice : IDisposable
    {
        public abstract I2cConnectionSettings ConnectionSettings { get; }

        public static I2cDevice Create(I2cConnectionSettings settings) { throw null; }

        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        public virtual ComponentInformation QueryComponentInformation() { throw null; }

        public abstract void Read(Span<byte> buffer);
        public virtual byte ReadByte() { throw null; }

        public abstract void Write(ReadOnlySpan<byte> buffer);
        public virtual void WriteByte(byte value) { }

        public abstract void WriteRead(ReadOnlySpan<byte> writeBuffer, Span<byte> readBuffer);
    }
}

namespace System.Device.Pwm
{
    public abstract partial class PwmChannel : IDisposable
    {
        public abstract double DutyCycle { get; set; }
        public abstract int Frequency { get; set; }

        public static PwmChannel Create(int chip, int channel, int frequency = 400, double dutyCyclePercentage = 0.5) { throw null; }

        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        public virtual ComponentInformation QueryComponentInformation() { throw null; }

        public abstract void Start();
        public abstract void Stop();
    }
}

namespace System.Device.Spi
{
    public enum DataFlow
    {
        MsbFirst = 0,
        LsbFirst = 1
    }

    public sealed partial class SpiConnectionSettings
    {
        public SpiConnectionSettings(int busId, int chipSelectLine = -1) { }

        public int BusId { get { throw null; } set { } }

        public int ChipSelectLine { get { throw null; } set { } }

        public Gpio.PinValue ChipSelectLineActiveState { get { throw null; } set { } }

        public int ClockFrequency { get { throw null; } set { } }

        public int DataBitLength { get { throw null; } set { } }

        public DataFlow DataFlow { get { throw null; } set { } }

        public SpiMode Mode { get { throw null; } set { } }
    }

    public abstract partial class SpiDevice : IDisposable
    {
        public abstract SpiConnectionSettings ConnectionSettings { get; }

        public static SpiDevice Create(SpiConnectionSettings settings) { throw null; }

        public void Dispose() { }

        protected virtual void Dispose(bool disposing) { }

        public abstract void Read(Span<byte> buffer);
        public virtual byte ReadByte() { throw null; }

        public abstract void TransferFullDuplex(ReadOnlySpan<byte> writeBuffer, Span<byte> readBuffer);
        public abstract void Write(ReadOnlySpan<byte> buffer);
        public virtual void WriteByte(byte value) { }
    }

    public enum SpiMode
    {
        Mode0 = 0,
        Mode1 = 1,
        Mode2 = 2,
        Mode3 = 3
    }
}